### ISSUE TITLE
Bug: DROP DOWN MENU DOES NOT SCROLL NOR HAS CLOSE WINDOW

### ISSUE THREAD

**Issue by ORCANLRC** [rodekruis/cash-program-design-wizard#537]
**Describe the bug**
when logging in from Ethiopia viw two types of browsers

**To Reproduce**
1. Go to '...' - 

- internet explorer
- google chrome 

2. Click on '.Drop multiple menu in any question"
3. Try to scroll
4. See error: Does not scroll

**Expected behavior**
In all other user test the multiple choce menu scroll and close function works 
**Screenshots**

@stefania marcuzzi to add 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elwinschmitz** [comment]
The missing scrollbar is caused by an (already long outstanding) existing issue in Ionic, see: https://github.com/ionic-team/ionic-framework/issues/18487

But a workaround is possible, fortunately.

Regarding the closing of the pop-up:
This is possible through the "Cancel"-button, by clicking 'outside' the pop-up or pressing the `ESC`-key on the keyboard.

**Comment by elwinschmitz** [comment]
The issue seems worse now. :/
At least on an iPhone...

**Comment by elwinschmitz** [comment]
I can't seem to reproduce the issue of "not being able to scroll" anymore on the development/local versions of the client/front-end app.

So closing this (at least for now)
